# Generated by Django 3.1.5 on 2021-06-22 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sbid', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('fashion', 'fashion'), ('toys', 'toys'), ('electronics', 'electronics'), ('phone', 'phone'), ('laptop', 'laptop'), ('book', 'books'), ('furniture', 'furniture')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
