# Generated by Django 3.1.5 on 2021-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_clisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clisting',
            new_name='listings',
        ),
    ]
