# Generated by Django 3.2.4 on 2021-06-24 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210624_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='nbid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
