# Generated by Django 3.2.4 on 2021-06-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='auctions.listings'),
        ),
    ]
