# Generated by Django 3.2.4 on 2021-06-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listing_id',
        ),
    ]
