# Generated by Django 3.2.4 on 2021-06-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_listing_watchlist_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(),
        ),
    ]
