# Generated by Django 3.2.4 on 2021-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wins',
            name='user',
            field=models.IntegerField(),
        ),
    ]
