# Generated by Django 3.2.4 on 2021-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_wins_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wins',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wins',
            name='owner',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wins',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wins',
            name='winbid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
