# Generated by Django 3.2.4 on 2021-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210629_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wins',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
