# Generated by Django 3.2.4 on 2021-07-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_wins_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'fashion'), ('toys', 'toys'), ('electronics', 'electronics'), ('phone', 'phone'), ('laptop', 'laptop'), ('book', 'books'), ('furniture', 'furniture')], default='none', max_length=20),
        ),
    ]
