# Generated by Django 3.2.4 on 2021-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'fashion'), ('toys', 'toys'), ('electronics', 'electronics'), ('antique', 'antique'), ('laptop', 'laptop'), ('book', 'books'), ('furniture', 'furniture')], default='none', max_length=20),
        ),
    ]
