# Generated by Django 4.0.4 on 2022-06-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wins',
            name='image',
            field=models.ImageField(upload_to='c_images/'),
        ),
    ]
