# Generated by Django 4.0.4 on 2022-06-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_wins_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='ldate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='times_bidded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wins',
            name='ldate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wins',
            name='times_bidded',
            field=models.IntegerField(default=0),
        ),
    ]
